version: '3.9'
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_IMPLEMENTATION=userspace
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - FIREWALL_VPN_INPUT_PORTS=${FIREWALL_VPN_INPUT_PORTS}
      - BLOCK_MALICIOUS=off
      - SERVER_REGIONS=Europe
    volumes:
      - gluetun:/gluetun
    dns:
      - 1.1.1.1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "ping" ,"-c1", "ifconfig.co" ]
  tailscale:
    container_name: tailscale-arr
    hostname: arr
    image: ghcr.io/tailscale/tailscale
    stdin_open: true
    environment:
      - TS_AUTH_KEY=${TS_AUTH_KEY}
      - TS_USERSPACE=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
    healthcheck:
      test: [ "CMD", "ping" ,"-c1", "example.com" ]
      interval: 30s
      timeout: 2s
      retries: 2
      start_period: 5s
    links:
      - 'gluetun:transmission'
      - 'gluetun:radarr'
      - 'gluetun:sonarr'
      - 'gluetun:prowlarr'
    volumes:
      - tailscalevarlib:/var/lib
    restart: unless-stopped
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:4.0.3
    stdin_open: true
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - '/mnt/data/torrents:/torrents'
      - '/srv/transmission:/config'
      - '/srv/transmission:/etc/transmission'
      - '/srv/transmission/downloads:/downloads'
    network_mode: 'service:gluetun'
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/radarr:/config
      - /srv/radarr/downloads:/downloads
      - /mnt/data/torrents:/data
    network_mode: 'service:gluetun'
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/sonarr:/config
      - /srv/sonarr/downloads:/downloads
      - /mnt/data/torrents:/data
    network_mode: 'service:gluetun'
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/prowlarr:/config
    network_mode: 'service:gluetun'
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    depends_on:
      gluetun:
        condition: service_healthy
  nginx:
    container_name: nginx-arr
    image: public.ecr.aws/nginx/nginx:1
    stdin_open: true
    network_mode: 'service:tailscale'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './nginx/shared.conf:/etc/nginx/conf.d/shared.conf:ro'
      - './nginx/index.html:/usr/share/nginx/html/index.html:ro'
      - '/etc/letsencrypt/live/example.com/fullchain.pem:/etc/ssl/fullchain.pem:ro'
      - '/etc/letsencrypt/live/example.com/privkey.pem:/etc/ssl/privkey.pem:ro'
    depends_on:
      tailscale:
        condition: service_healthy
    restart: unless-stopped
volumes:
  gluetun:
  tailscalevarlib:
